version: '3.0'
services:
  api:
    build: ./server/
    container_name: api
    ports:
      - "3700:3700"
    command: npm start  
    environment:
      MONGO_URI: mongodb://youssef:youssef@db:27017
    volumes:
      - "./server/:/app"  
      - "/app/node_modules"
  web:
    build: ./client/
    container_name: web
    ports:
      - "3000:3000"
    command: npm start  
    volumes:
      - "./client/:/app"  
      - "/app/node_modules"
  db: 
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: youssef
      MONGO_INITDB_ROOT_PASSWORD: youssef
    volumes:
      - db-data:/data/db
volumes:
  db-data: {}        
      
    
